### ISSUE TITLE
Archive download doesn't work on Firefox when "manual select" is used.

### ISSUE THREAD

**Issue by fireattack** [Mayriad/Mayriads-EH-Download-Shortcuts#1]
To have this bug, you need to

1. use Firefox (it works fine on Chrome) + Tampermonkey
2. Go to your [setting](https://e-hentai.org/uconfig.php) and set "Archiver Settings" to either "manual select, manual start" or "manual select, auto start".

STR:

1. Check prerequisites above. 
2. Open https://e-hentai.org/?f_search=春工房
3. Download the very first gallery, should be `(IDOL STAR FESTIV@L 07) [Haru Koubou (Harukoubou Norimaki)] MILLIERO.03 (THE IDOLM@STER MILLION LIVE!)`.

What happens:

It starts "loading", and I can see from the Network Tool that it successfully opens both the gallery detail page and the archiver.php page. However, downloading doesn't happen after it and it keeps retrying. 

It works fine on Chrome, and also works fine if I change the setting to any of the "auto select" options (regardless auto start or not).

**Comment by Mayriad** [comment]
Thank you very much for all the testing you did, but I am shocked that it even works on Firefox in the first place. I just found out that Firefox does not handle display: none correctly, so I think this script would not work at all. The next update is coming very soon and it will address this problem, but if you would like to test it again, you can replace these lines
```
iframe.style.display = 'none';
```
with
```
iframe.style.visibility = 'hidden';
```
And see if the script will work. Otherwise, I cannot reproduce your problem and your extensive testing filtered out a lot of things, so this is my only guess at the moment.

**Comment by fireattack** [comment]
Yeah, it works after I changed both lines to "hidden".

**Comment by Mayriad** [comment]
That was quick. Thanks again for your feedback.

**Comment by fireattack** [comment]
I do think it's probably better to use `GM_xmlhttpRequest` instead, if you're considering refactoring in future.

**Comment by Mayriad** [comment]
Yes, I already know it, but as I mentioned in the readme, it will require rewriting a large proportion of the code and it can be difficult and time-consuming for me since I am not a programmer. Therefore, I cannot consider it anytime soon.
